/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function StartupRocket(props) {
  const { nodes, materials } = useGLTF('/models/NewModels/compressed_startuprocket.glb')
  return (
    <group {...props} dispose={null} position={[-0.100, 1.076, -65.157]} scale={0.5112}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial.geometry}
        material={materials.Fire}
        position={[-0.144, -0.574, -0.007]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial001.geometry}
        material={materials.Blue_Plastic}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial002.geometry}
        material={materials.DarkGrey_Plastic}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial003.geometry}
        material={materials.Chrome}
        position={[0.444, 0.324, -0.001]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial004.geometry}
        material={materials.Red_Plastic}
        position={[0.521, 0.445, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial005.geometry}
        material={materials.White_Plastic}
        position={[0.329, 0.142, -0.004]}
      />
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial006.geometry}
        material={materials.Stand_Brass}
      /> */}
    </group>
  )
}

useGLTF.preload('/models/NewModels/compressed_startuprocket.glb')


